/**
 * types.ts
 * Phase 30 - Admin & Club Financial Dashboard (Read-Only)
 *
 * Immutable view model types for financial dashboard.
 *
 * HARD CONSTRAINTS:
 * - All types are read-only
 * - No balances stored (must be derived)
 * - All numbers traceable to ledger entries
 * - No payment concepts
 */

import { PlayerId } from '../security/Identity';
import { TableId, HandId } from '../security/AuditLog';
import { ClubId } from '../club/ClubTypes';
import { AdminId, AdminCreditReason } from '../admin-credit/AdminCreditTypes';
import { AttributionSource, AttributionPartyType } from '../ledger/LedgerTypes';

// ============================================================================
// Time Range Types
// ============================================================================

/**
 * Time range for filtering aggregations
 */
export interface DashboardTimeRange {
  readonly fromTimestamp: number;
  readonly toTimestamp: number;
}

/**
 * Create a time range for the last N hours
 */
export function createLastHoursRange(hours: number): DashboardTimeRange {
  const now = Date.now();
  return {
    fromTimestamp: now - hours * 60 * 60 * 1000,
    toTimestamp: now,
  };
}

/**
 * Create a time range for the last N days
 */
export function createLastDaysRange(days: number): DashboardTimeRange {
  const now = Date.now();
  return {
    fromTimestamp: now - days * 24 * 60 * 60 * 1000,
    toTimestamp: now,
  };
}

/**
 * Create an all-time range
 */
export function createAllTimeRange(): DashboardTimeRange {
  return {
    fromTimestamp: 0,
    toTimestamp: Date.now(),
  };
}

// ============================================================================
// Player Finance Summary
// ============================================================================

/**
 * Financial summary for a player
 *
 * Shows chips in, chips out, and net position.
 * All values are derived from ledger entries.
 */
export interface PlayerFinanceSummary {
  readonly playerId: PlayerId;
  readonly timeRange: DashboardTimeRange;

  /** Total chips received (winnings + credits) */
  readonly totalChipsIn: number;

  /** Chips from pot winnings */
  readonly chipsFromWinnings: number;

  /** Chips from admin credits */
  readonly chipsFromCredits: number;

  /** Total chips lost (rake + losses) */
  readonly totalChipsOut: number;

  /** Chips lost in pots */
  readonly chipsToLosses: number;

  /** Chips paid as rake (indirect, via pot) */
  readonly chipsToRake: number;

  /** Net position (totalChipsIn - totalChipsOut) */
  readonly netPosition: number;

  /** Number of hands played */
  readonly handsPlayed: number;

  /** Number of tables played at */
  readonly tablesPlayed: number;

  /** Breakdown by club */
  readonly byClub: ReadonlyMap<ClubId, number>;
}

/**
 * Create empty player finance summary
 */
export function emptyPlayerFinanceSummary(
  playerId: PlayerId,
  timeRange: DashboardTimeRange
): PlayerFinanceSummary {
  return {
    playerId,
    timeRange,
    totalChipsIn: 0,
    chipsFromWinnings: 0,
    chipsFromCredits: 0,
    totalChipsOut: 0,
    chipsToLosses: 0,
    chipsToRake: 0,
    netPosition: 0,
    handsPlayed: 0,
    tablesPlayed: 0,
    byClub: new Map(),
  };
}

// ============================================================================
// Club Finance Summary
// ============================================================================

/**
 * Financial summary for a club
 *
 * Shows player activity, rake generated, and credit flow.
 * All values are derived from ledger entries.
 */
export interface ClubFinanceSummary {
  readonly clubId: ClubId;
  readonly timeRange: DashboardTimeRange;

  /** Number of unique players */
  readonly playerCount: number;

  /** Total chips credited to players via admin credits */
  readonly totalCredits: number;

  /** Total rake generated by this club */
  readonly totalRake: number;

  /** Club's share of rake */
  readonly clubRakeShare: number;

  /** Platform's share of rake (from this club) */
  readonly platformRakeShare: number;

  /** Agent commissions (if any) */
  readonly agentCommissions: number;

  /** Number of hands played */
  readonly handsPlayed: number;

  /** Total pot volume */
  readonly totalPotVolume: number;

  /** Number of active tables */
  readonly activeTables: number;

  /** Breakdown by table */
  readonly byTable: ReadonlyMap<TableId, ClubTableSummary>;

  /** Breakdown by admin credit reason */
  readonly creditsByReason: Readonly<Record<AdminCreditReason, number>>;
}

/**
 * Summary for a table within a club
 */
export interface ClubTableSummary {
  readonly tableId: TableId;
  readonly handsPlayed: number;
  readonly totalRake: number;
  readonly totalPotVolume: number;
  readonly playerCount: number;
}

/**
 * Create empty club finance summary
 */
export function emptyClubFinanceSummary(
  clubId: ClubId,
  timeRange: DashboardTimeRange
): ClubFinanceSummary {
  return {
    clubId,
    timeRange,
    playerCount: 0,
    totalCredits: 0,
    totalRake: 0,
    clubRakeShare: 0,
    platformRakeShare: 0,
    agentCommissions: 0,
    handsPlayed: 0,
    totalPotVolume: 0,
    activeTables: 0,
    byTable: new Map(),
    creditsByReason: {
      OFFLINE_BUYIN: 0,
      PROMOTION: 0,
      TESTING: 0,
      CORRECTION: 0,
    },
  };
}

// ============================================================================
// Platform Finance Summary
// ============================================================================

/**
 * Financial summary for the entire platform
 *
 * Aggregates all clubs, players, and revenue.
 * Revenue = rake ONLY (admin credits are NOT revenue).
 */
export interface PlatformFinanceSummary {
  readonly timeRange: DashboardTimeRange;

  /** Total platform rake revenue */
  readonly totalRakeRevenue: number;

  /** Total rake collected across all clubs */
  readonly totalRakeCollected: number;

  /** Total admin credits issued (NOT revenue) */
  readonly totalCreditsIssued: number;

  /** Number of active clubs */
  readonly activeClubs: number;

  /** Number of unique players */
  readonly uniquePlayers: number;

  /** Number of hands played */
  readonly handsPlayed: number;

  /** Total pot volume */
  readonly totalPotVolume: number;

  /** Breakdown by club */
  readonly byClub: ReadonlyMap<ClubId, ClubRakeSummary>;

  /** Breakdown by source type */
  readonly bySource: Readonly<Record<AttributionSource, number>>;
}

/**
 * Rake summary for a club (from platform perspective)
 */
export interface ClubRakeSummary {
  readonly clubId: ClubId;
  readonly totalRake: number;
  readonly platformShare: number;
  readonly clubShare: number;
  readonly handsPlayed: number;
}

/**
 * Create empty platform finance summary
 */
export function emptyPlatformFinanceSummary(
  timeRange: DashboardTimeRange
): PlatformFinanceSummary {
  return {
    timeRange,
    totalRakeRevenue: 0,
    totalRakeCollected: 0,
    totalCreditsIssued: 0,
    activeClubs: 0,
    uniquePlayers: 0,
    handsPlayed: 0,
    totalPotVolume: 0,
    byClub: new Map(),
    bySource: {
      HAND_SETTLEMENT: 0,
      TIME_FEE: 0,
      TOURNAMENT_PAYOUT: 0,
      REBUY: 0,
      ADJUSTMENT: 0,
      BONUS: 0,
      TOP_UP: 0,
    },
  };
}

// ============================================================================
// Table Finance Summary
// ============================================================================

/**
 * Financial summary for a single table
 *
 * Shows hand activity, rake, and player participation.
 */
export interface TableFinanceSummary {
  readonly tableId: TableId;
  readonly clubId: ClubId;
  readonly timeRange: DashboardTimeRange;

  /** Number of hands played */
  readonly handsPlayed: number;

  /** Total pot volume */
  readonly totalPotVolume: number;

  /** Average pot size */
  readonly averagePotSize: number;

  /** Total rake collected */
  readonly totalRake: number;

  /** Average rake per hand */
  readonly averageRakePerHand: number;

  /** Number of unique players */
  readonly uniquePlayers: number;

  /** List of player IDs who participated */
  readonly playerIds: readonly PlayerId[];

  /** Breakdown by hand (last N hands) */
  readonly recentHands: readonly HandSummary[];
}

/**
 * Summary of a single hand
 */
export interface HandSummary {
  readonly handId: HandId;
  readonly timestamp: number;
  readonly potSize: number;
  readonly rake: number;
  readonly playerCount: number;
}

/**
 * Create empty table finance summary
 */
export function emptyTableFinanceSummary(
  tableId: TableId,
  clubId: ClubId,
  timeRange: DashboardTimeRange
): TableFinanceSummary {
  return {
    tableId,
    clubId,
    timeRange,
    handsPlayed: 0,
    totalPotVolume: 0,
    averagePotSize: 0,
    totalRake: 0,
    averageRakePerHand: 0,
    uniquePlayers: 0,
    playerIds: [],
    recentHands: [],
  };
}

// ============================================================================
// Access Role Types
// ============================================================================

/**
 * Dashboard access role
 */
export type DashboardRole =
  | 'PLATFORM_ADMIN'
  | 'CLUB_OWNER'
  | 'CLUB_MANAGER'
  | 'PLAYER';

/**
 * Dashboard access scope
 */
export interface DashboardAccessScope {
  readonly role: DashboardRole;
  readonly userId: string;
  readonly clubIds?: readonly ClubId[];  // For club owners/managers
  readonly tableIds?: readonly TableId[]; // For managers with table restrictions
}

/**
 * Dashboard query result
 */
export interface DashboardQueryResult<T> {
  readonly success: boolean;
  readonly data?: T;
  readonly accessDenied?: boolean;
  readonly error?: string;
}

// ============================================================================
// Aggregation Input Types
// ============================================================================

/**
 * Ledger entry for aggregation (simplified view)
 */
export interface AggregationEntry {
  readonly entryId: string;
  readonly timestamp: number;
  readonly source: AttributionSource;
  readonly partyType: AttributionPartyType;
  readonly playerId?: PlayerId;
  readonly clubId?: ClubId;
  readonly tableId?: TableId;
  readonly handId?: HandId;
  readonly delta: number;
  readonly metadata?: Readonly<Record<string, unknown>>;
}

/**
 * Convert ledger entry to aggregation entry
 */
export function toAggregationEntry(entry: {
  readonly entryId: string;
  readonly timestamp: number;
  readonly source: AttributionSource;
  readonly affectedParty: {
    readonly partyType: AttributionPartyType;
    readonly playerId?: PlayerId;
    readonly clubId?: ClubId;
  };
  readonly clubId?: ClubId;
  readonly tableId?: TableId;
  readonly handId?: HandId;
  readonly delta: number;
  readonly metadata?: Readonly<Record<string, unknown>>;
}): AggregationEntry {
  return {
    entryId: entry.entryId,
    timestamp: entry.timestamp,
    source: entry.source,
    partyType: entry.affectedParty.partyType,
    playerId: entry.affectedParty.playerId,
    clubId: entry.clubId ?? entry.affectedParty.clubId,
    tableId: entry.tableId,
    handId: entry.handId,
    delta: entry.delta,
    metadata: entry.metadata,
  };
}

// ============================================================================
// Utility Functions
// ============================================================================

/**
 * Calculate integer average (avoiding floating point)
 */
export function integerAverage(total: number, count: number): number {
  if (count === 0) return 0;
  return Math.floor(total / count);
}

/**
 * Check if entry is within time range
 */
export function isInTimeRange(
  timestamp: number,
  timeRange: DashboardTimeRange
): boolean {
  return timestamp >= timeRange.fromTimestamp && timestamp <= timeRange.toTimestamp;
}
