/**
 * Network Module
 * Phase 12 - Realtime multiplayer networking layer
 *
 * Authoritative server architecture for club-based poker rooms.
 */

// Error types
export {
  RejectCode,
  NetworkError,
  ConnectionError,
  RoomError,
  SeatError,
  ActionError,
  SyncError,
  Errors,
  RejectionResponse,
  toRejectionResponse,
} from './NetworkErrors';

// Protocol types
export {
  ClubId,
  RoomId,
  TableId,
  PlayerId,
  SessionId,
  HandId,
  MessageId,
  MessageHeader,
  TableContext,
  ActionType,
  PlayerAction,
  ClientIntentType,
  ClientIntent,
  JoinRoomIntent,
  LeaveRoomIntent,
  TakeSeatIntent,
  LeaveSeatIntent,
  BuyInIntent,
  StandUpIntent,
  SitBackIntent,
  PlayerActionIntent,
  RequestSyncIntent,
  HeartbeatIntent,
  ServerEventType,
  ServerEvent,
  AckEvent,
  RejectEvent,
  RoomJoinedEvent,
  RoomLeftEvent,
  PlayerJoinedEvent,
  PlayerLeftEvent,
  SeatTakenEvent,
  SeatVacatedEvent,
  PlayerSatOutEvent,
  PlayerSatBackEvent,
  HandStartedEvent,
  ActionPerformedEvent,
  StreetChangedEvent,
  PotUpdatedEvent,
  ShowdownEventMsg,
  HandEndedEvent,
  SnapshotEvent,
  DiffEvent,
  DiffOperation,
  HeartbeatAckEvent,
  PlayerDisconnectedEvent,
  PlayerReconnectedEvent,
  PlayerTimeoutWarningEvent,
  PlayerTimedOutEvent,
  Card,
  SeatSnapshot,
  TableSnapshot,
  RoomSnapshot,
  RoomConfig,
  createMessageId,
  createMessageHeader,
  createTableContext,
  isClientIntent,
  isServerEvent,
  isActionIntent,
  isAck,
  isReject,
  isSnapshot,
  isDiff,
} from './Protocol';

// Room state
export {
  SeatStatus,
  Seat,
  Street,
  Table,
  PlayerInRoom,
  Room,
  Club,
  createEmptySeat,
  seatPlayer,
  updateSeat,
  vacateSeat,
  createTable,
  updateTable,
  updateTableSeat,
  incrementSequence,
  getSeatedPlayers,
  getActivePlayers,
  getActingPlayers,
  getSeatByPlayerId,
  getNextActiveSeat,
  canStartHand,
  createRoom,
  addPlayerToRoom,
  removePlayerFromRoom,
  updatePlayerInRoom,
  updateRoomTable,
  getTableById,
  createClub,
  addRoomToClub,
  updateClubRoom,
  getRoomById,
  generateSeatSnapshot,
  generateTableSnapshot,
  generateRoomSnapshot,
  isValidSeatIndex,
  isSeatEmpty,
  isPlayerSeated,
  isHandInProgress,
  isPlayerTurn,
} from './RoomState';

// Sync engine
export {
  StoredSnapshot,
  SyncState,
  SyncResult,
  SyncEngine,
  getSyncEngine,
  resetSyncEngine,
} from './SyncEngine';

// Connection session
export {
  SessionStatus,
  Session,
  SessionConfig,
  DisconnectEvent,
  ReconnectEvent,
  SessionManager,
  getSessionManager,
  resetSessionManager,
} from './ConnectionSession';

// Room authority
export {
  AuthorityConfig,
  IntentResult,
  EventCallback,
  RoomAuthority,
  createRoomAuthority,
} from './RoomAuthority';
